// The stylesheet for the navigation shell, appended after tools/docs/styles.mjs.
// It is additive: the handful of rules that supersede the old single-column
// layout win on source order, and no rule here introduces a url(), an @import or
// an @font-face, because the page has to render identically with the network
// unplugged.
//
// How one-panel-at-a-time works, and why it is built this way:
//   * `.pane`/`.phase` children of #panes are hidden; `:target` shows the one the
//     address bar names. That is the whole mechanism, and it needs no JavaScript.
//   * With no fragment at all, the default panel shows — which panel that is
//     belongs to layout.mjs, so those three rules are generated by
//     `defaultPaneRules` below rather than written here. The default panel is the
//     LAST child of #panes so that `#panes > :target ~ #<default>` can hide it
//     once a panel is chosen — a general sibling combinator, supported
//     everywhere, rather than `:has()`.
//     DOM order is invisible to the reader because exactly one panel is ever
//     displayed.
//   * `:has()` appears only in progressive enhancements (deep links into a panel,
//     the current-panel marker in the nav). Where it is missing, the page still
//     switches panels correctly; it just does not highlight, and the script sets
//     aria-current anyway.
export const SHELL_STYLES = `
.masthead { max-width: 1240px; margin: 0 auto; padding: 26px 20px 12px; }
.masthead h1 { font-size: 28px; }
.masthead .lede { margin-bottom: 10px; }
.shell {
  max-width: 1240px;
  margin: 0 auto;
  padding: 0 20px 64px;
  display: grid;
  grid-template-columns: 252px minmax(0, 1fr);
  gap: 26px;
  align-items: start;
}
.sidenav {
  position: sticky;
  top: 12px;
  align-self: start;
  max-height: calc(100vh - 24px);
  overflow-y: auto;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 14px 10px;
  font-size: 14px;
}
.nav-group { margin: 0 0 16px; }
.nav-group:last-of-type { margin-bottom: 0; }
.nav-label {
  font-family: var(--mono);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.09em;
  color: var(--muted);
  margin: 0 0 6px;
  padding: 0 8px;
}
.nav-list { list-style: none; margin: 0; padding: 0; }
.nav-list li { margin: 0; }
.nav-list a {
  display: flex;
  gap: 8px;
  align-items: baseline;
  padding: 6px 8px;
  border-radius: 6px;
  border-left: 3px solid transparent;
  text-decoration: none;
  color: var(--fg);
}
.nav-list a:hover { background: var(--cluster); }
.nav-num { font-family: var(--mono); font-size: 12px; color: var(--muted); min-width: 1.1em; }
.nav-name { flex: 1 1 auto; }
.nav-flag { font-family: var(--mono); font-size: 10px; color: var(--muted); }
.nav-list a[aria-current='page'] {
  background: var(--cluster);
  border-left-color: var(--accent);
  font-weight: 600;
}
.nav-list a[aria-current='page'] .nav-num { color: var(--accent); }
.nav-list li.is-empty a .nav-name { color: var(--muted); }
.nav-hint { font-family: var(--mono); font-size: 11px; color: var(--muted); margin: 14px 0 0; padding: 0 8px; }
kbd {
  font-family: var(--mono);
  font-size: 11px;
  border: 1px solid var(--line);
  border-bottom-width: 2px;
  border-radius: 4px;
  padding: 0 4px;
  background: var(--cluster);
}
#panes > .pane, #panes > .phase {
  display: none;
  scroll-margin-top: 16px;
  margin: 0;
}
#panes > .pane:target, #panes > .phase:target { display: block; }
#panes > .pane:has(:target), #panes > .phase:has(:target) { display: block; }
.pane {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 10px;
  padding: 22px;
}
.pane > :last-child, .phase > :last-child { margin-bottom: 0; }
.pane > h2, .phase > .phase-head h2 { font-size: 24px; }
a:focus-visible, button:focus-visible, summary:focus-visible, [tabindex]:focus-visible {
  outline: 3px solid var(--accent);
  outline-offset: 2px;
  border-radius: 4px;
}
.stat-row {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
  gap: 10px;
  margin: 0 0 20px;
}
.stat { border: 1px solid var(--line); border-radius: 8px; padding: 10px 12px; }
.stat-value { font-family: var(--mono); font-size: 22px; line-height: 1.2; }
.stat-of { font-size: 13px; color: var(--muted); }
.stat-label { font-size: 13px; margin-top: 2px; }
.stat-source { font-family: var(--mono); font-size: 11px; color: var(--muted); margin-top: 3px; }
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
  gap: 10px;
  list-style: none;
  margin: 0;
  padding: 0;
}
.card { margin: 0; }
.card a {
  display: flex;
  flex-direction: column;
  gap: 2px;
  height: 100%;
  border: 1px solid var(--line);
  border-radius: 8px;
  padding: 10px 12px;
  text-decoration: none;
  color: var(--fg);
}
.card a:hover { border-color: var(--line-strong); background: var(--cluster); }
.card-empty a { border-style: dashed; }
.card-num { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; color: var(--muted); }
.card-name { font-size: 15px; }
.card-flag { font-family: var(--mono); font-size: 11px; color: var(--muted); }
.callout {
  border: 1px solid var(--line);
  border-left-width: 4px;
  border-radius: 8px;
  padding: 12px 16px;
  margin: 0 0 20px;
  background: var(--cluster);
}
.callout > :last-child { margin-bottom: 0; }
/* A callout title is a sentence, not a section label: the uppercase h3 treatment
   from the base sheet turns a drift finding into shouting. */
.callout h3 {
  margin-top: 0;
  font-size: 16px;
  text-transform: none;
  letter-spacing: 0;
  color: var(--fg);
}
.callout-note { border-left-color: var(--accent); }
.callout-drift { border-left-color: var(--fail); }
.callout-drift h3 { color: var(--fail); }
.callout-clean { border-left-color: var(--done); }
.callout-clean h3 { color: var(--done); }
.caveat-list { margin: 0; padding-left: 20px; font-size: 14px; }
.caveat-list li { margin: 0 0 8px; }
.caveat-list li:last-child { margin-bottom: 0; }
.source-banner { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin: 0 0 8px; }
.source-label { font-size: 14px; }
.source-note { font-size: 14px; color: var(--muted); margin: 0 0 20px; max-width: 78ch; }
.pill-source { color: var(--accent); }
.pill-auth { color: var(--muted); text-transform: none; letter-spacing: 0.03em; }
.chip-row { display: flex; flex-wrap: wrap; gap: 8px; list-style: none; margin: 0 0 18px; padding: 0; }
.chip {
  display: inline-block;
  font-family: var(--mono);
  font-size: 12px;
  text-decoration: none;
  color: var(--fg);
  border: 1px solid var(--line);
  border-radius: 999px;
  padding: 3px 11px;
  background: var(--panel);
}
.chip:hover { border-color: var(--line-strong); }
.auth-legend { display: flex; flex-wrap: wrap; gap: 14px; list-style: none; margin: 0 0 8px; padding: 0; font-size: 13px; }
.auth-legend li { margin: 0; display: flex; gap: 6px; align-items: baseline; }
.verb {
  font-family: var(--mono);
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 0.06em;
  border: 1px solid currentColor;
  border-radius: 4px;
  padding: 1px 6px;
}
.verb-get { color: var(--s1); }
.verb-post { color: var(--s2); }
.verb-patch { color: var(--s3); }
.verb-put { color: var(--s4); }
.verb-delete { color: var(--fail); }
.api-table td { vertical-align: top; }
.api-head { display: flex; gap: 8px; align-items: baseline; }
.api-path { font-size: 14px; font-weight: 600; background: none; padding: 0; }
.api-summary { display: block; color: var(--muted); font-size: 13px; margin-top: 4px; max-width: 44ch; }
.api-request { font-size: 13px; max-width: 24ch; }
.status-list { list-style: none; margin: 0; padding: 0; font-size: 13px; }
.status-list li { display: flex; gap: 7px; margin: 0 0 3px; }
.status { font-family: var(--mono); font-size: 12px; font-weight: 700; }
.status-ok { color: var(--done); }
.status-client { color: var(--pending); }
.status-server { color: var(--fail); }
.table-scroll { max-height: 340px; overflow-y: auto; }
.ch-axis { stroke: var(--line-strong); stroke-width: 1; }
.ch-axis-title { font-family: var(--mono); font-size: 11px; fill: var(--muted); }
.ch-line { fill: none; stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }
.ch-k1 { stroke: var(--s1); }
.ch-k2 { stroke: var(--s2); }
.ch-k3 { stroke: var(--s3); }
.ch-k4 { stroke: var(--s4); }
.ch-k5 { stroke: var(--s5); }
.ch-dot { stroke: var(--panel); stroke-width: 1; }
.ch-point { stroke: var(--panel); stroke-width: 1.5; }
.ch-day-rule { stroke: var(--line-strong); stroke-width: 1; stroke-dasharray: 2 4; }
.ch-zero { font-family: var(--mono); font-size: 9px; fill: var(--muted); }
footer.page-foot { max-width: 1240px; margin: 0 auto; padding: 0 20px 40px; }
@media (max-width: 950px) {
  .shell { grid-template-columns: minmax(0, 1fr); gap: 14px; padding-bottom: 40px; }
  .sidenav { position: sticky; top: 0; z-index: 5; max-height: none; padding: 10px 8px; border-radius: 10px; }
  .nav-group { margin: 0 0 8px; }
  .nav-list { display: flex; gap: 6px; overflow-x: auto; padding-bottom: 4px; }
  .nav-list a { white-space: nowrap; border-left: 0; border-bottom: 3px solid transparent; }
  .nav-list a[aria-current='page'] { border-left-color: transparent; border-bottom-color: var(--accent); }
  .nav-name { flex: 0 0 auto; }
  .nav-hint { margin-top: 8px; }
  /* The nav is sticky and about 190px tall once it has wrapped, so a panel
     scrolled to y=0 would open underneath it with its own heading hidden. */
  #panes > .pane, #panes > .phase { scroll-margin-top: 200px; }
  .pane, .phase { padding: 16px 14px; }
}
/* The lab-trajectory pane. A slot is a state, not a height: there is no scale to
   share between a boolean, a percentage and a pod count, so the three states are
   distinguished by stroke, not by size — solid for measured, dashed for declared,
   faint dotted for a phase that declares no measurement of that question. */
.tj-tally { display: flex; flex-wrap: wrap; gap: 22px; list-style: none; margin: 0 0 20px; padding: 0; font-size: 13px; color: var(--muted); }
.tj-tally li { margin: 0; display: flex; gap: 7px; align-items: baseline; }
.tj-n { font-family: var(--mono); font-size: 21px; color: var(--fg); }
.score { display: grid; grid-template-columns: repeat(auto-fit, minmax(330px, 1fr)); gap: 12px; list-style: none; margin: 0; padding: 0; }
.score > li { margin: 0; border: 1px solid var(--line); border-radius: 8px; padding: 12px 14px; }
.score-head { display: flex; flex-wrap: wrap; gap: 10px; align-items: baseline; justify-content: space-between; }
.score-name { font-size: 15px; font-weight: 600; }
.pill-open { color: var(--muted); }
.traj { border: 1px solid var(--line); border-radius: 8px; padding: 14px; background: var(--panel); margin: 0 0 20px; }
.traj svg { max-width: 100%; height: auto; display: block; }
.traj-head { display: flex; flex-wrap: wrap; gap: 10px; align-items: baseline; justify-content: space-between; }
.traj-name { font-size: 16px; font-weight: 600; }
.traj-count { font-family: var(--mono); font-size: 11px; color: var(--muted); }
.traj-q { font-size: 14px; color: var(--muted); margin: 4px 0 12px; max-width: 88ch; }
.tj-phase { font-family: var(--mono); font-size: 10px; fill: var(--muted); }
.tj-state { font-family: var(--mono); font-size: 10px; }
.tj-value { font-family: var(--mono); font-size: 12px; fill: var(--fg); }
.tj-box { fill: none; stroke-width: 1.2; }
rect.tj-box.tj-m { fill: var(--cluster); stroke: var(--done); stroke-width: 2; }
rect.tj-box.tj-d { stroke: var(--pending); stroke-dasharray: 5 4; }
rect.tj-box.tj-n { stroke: var(--line); stroke-dasharray: 2 5; }
text.tj-state.tj-m { fill: var(--done); }
text.tj-state.tj-d { fill: var(--pending); }
text.tj-state.tj-n { fill: var(--muted); }
.tj-na-note { font-family: var(--mono); font-size: 11px; color: var(--muted); margin: 10px 0 0; }
.tj-plan { list-style: none; margin: 12px 0 0; padding: 0; }
.tj-plan > li { margin: 0 0 12px; padding: 0 0 0 12px; border-left: 3px solid var(--line); }
.tj-plan > li.is-measured { border-left-color: var(--done); }
.tj-plan > li.is-declared { border-left-color: var(--pending); }
.tj-when { display: flex; flex-wrap: wrap; gap: 8px; align-items: baseline; margin: 0 0 3px; font-family: var(--mono); font-size: 12px; color: var(--muted); }
.tj-read { margin: 0 0 3px; font-size: 14px; }
.tj-how { margin: 0; font-size: 14px; color: var(--muted); max-width: 92ch; }
.tj-k { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; margin-right: 5px; }
/* A phase pane, told as a story. The two handover blocks are quotes from a
   neighbouring phase rather than claims this phase makes, so they are set apart:
   amber on the way in (the residue phase N-1 left standing), accent on the way
   out (the sentence phase N+1 opens with). The thread above them is the same
   nine phases in order, so a reader always sees where in the sequence they are. */
.thread { display: flex; flex-wrap: wrap; gap: 6px; list-style: none; margin: 12px 0 18px; padding: 0; }
.thread li { margin: 0; }
.thread .chip { font-size: 11px; padding: 2px 9px; }
.thread .thread-num { color: var(--muted); margin-right: 5px; }
.thread li.here .chip { border-color: var(--accent); background: var(--cluster); font-weight: 600; }
.thread li.here .thread-num { color: var(--accent); }
.handover {
  border: 1px solid var(--line);
  border-left-width: 4px;
  border-radius: 8px;
  padding: 12px 14px;
  margin: 0 0 20px;
  background: var(--cluster);
}
.handover > :last-child { margin-bottom: 0; }
.hand-in { border-left-color: var(--pending); }
.hand-out { border-left-color: var(--accent); }
.hand-head { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); margin: 0 0 7px; }
.hand-line { margin: 0 0 6px; font-size: 14px; max-width: 92ch; }
.hand-k { font-family: var(--mono); font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: var(--muted); margin-right: 6px; }
.story-q { list-style: none; margin: 0 0 16px; padding: 0; font-size: 14px; }
.story-q li { display: flex; flex-wrap: wrap; gap: 8px; align-items: baseline; margin: 0 0 5px; }
@media (max-width: 950px) {
  .score { grid-template-columns: minmax(0, 1fr); }
}
@media print {
  .sidenav { display: none; }
  .shell { grid-template-columns: minmax(0, 1fr); }
  #panes > .pane, #panes > .phase { display: block; }
}
`

// The three rules that name the default panel: the one that shows when the
// address bar names no panel, and the two that hide it again once another panel
// is targeted. Generated because which panel opens the page is layout.mjs's
// decision, and duplicating that id in a stylesheet is how the two drift apart.
export const defaultPaneRules = ({ defaultPaneId }) =>
  [
    `#panes > #${defaultPaneId} { display: block; }`,
    `#panes > :target ~ #${defaultPaneId} { display: none; }`,
    `#panes > :has(:target) ~ #${defaultPaneId} { display: none; }`,
  ].join('\n')

// One rule per panel, generated so the nav can mark the current entry without
// JavaScript. Each panel gets two selectors: the panel itself being the target,
// and something inside it being the target (a deep link such as #api-images).
export const navCurrentRules = ({ paneIds, defaultPaneId }) => {
  const marker = `{background:var(--cluster);border-left-color:var(--accent);font-weight:600}`
  const perPane = paneIds
    .flatMap((id) => [
      `body:has(#${id}:target) [data-pane="${id}"]`,
      `body:has(#${id} :target) [data-pane="${id}"]`,
    ])
    .map((selector) => `${selector}${marker}`)
  const fallback = `body:not(:has(#panes :target)) [data-pane="${defaultPaneId}"]${marker}`
  return [...perPane, fallback].join('\n')
}
